
```{r setup, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(reshape)
library(ggplot2)
library(lubridate)
library(plotly)

```


```{r length_dist_2012}

corvina.all.2012.short<- read.csv('./data/corvina_length_monthly_2012.csv') 
corvina.all.2012.short$date = as.Date(corvina.all.2012.short$date, "%m/%d/%y")

corvina.all.2012 <- untable(corvina.all.2012.short[ , c(1,4)], num=corvina.all.2012.short[ ,5]) %>%
  mutate(label = month.abb[month(date)])

```

```{r plot}

p1<- ggplot(corvina.all.2012, aes(length_class, fill=factor(label, levels =    unique(label)))) +
    geom_histogram(binwidth = 1) +
    theme_minimal()+
    guides(fill=guide_legend(title="Month"))
   
ggplotly(p1)

```


This is two different approaches to convert lengths to age. The first is a formula I got from someone elses code. The second is the equation from [FAO](http://www.fao.org/docrep/w5449e/w5449e06.htm#4.4.5 the linearized catch curve based on length composition data):

$$t(L)=t_0 - 1/K * ln(1-L/L_{inf})$$


 ** the second seems better because we know that length/ age at maturity if 55cm/5years
```{r age_at_length}
#Model parameters fom Mug Villanueva (1994)
#Used the lower bound of the range

Linf = 122.1
to = -0.136
K = 0.121

#Equation from Dan's code
corvina.age1 <- log(1-(pmin(corvina.all.2012$length_class, Linf*.99))/(-K)) + to

#Equation from FAO 
#(http://www.fao.org/docrep/w5449e/w5449e06.htm#4.4.5 the linearized catch curve based on length composition data)

corvina.age2 <- to - (1/K) * log(1-corvina.all.2012$length_class/Linf)

corvina.all.2012$age_class1 = corvina.age1

corvina.all.2012$age_class2 = corvina.age2

```

```{r plot_length_age}
corvina.age.length <- unique(corvina.all.2012[,c('age_class2','length_class')])

ggplot(data = corvina.age.length, aes(x=age_class2, y=length_class)) +
  geom_point() +
  theme_minimal()

```

