---
title: "Inital Data Summary and Visulaization"
author: "Alex Smith"
date: "April 26, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(dplyr)
library(tidyr)
library(ggplot2)
```

```{r load_data}

d1=read.csv('./data/incopesca_catch.csv') %>%
  filter(Region=="Golfo de Nicoya") 

#reads in the clean data and filters out data for Gulf of Nicoya
```



```{r d_long}

d.GN.month= d1[3:16] %>%
              gather('month','catch',Jan:Dec)

#selects only the year, species and catch data then transforms into long format

look.up=data.frame(month=unique(d.GN.month$month), month.num=seq(1,12))
look.up$month=as.character(look.up$month)

#creates a look-up table to translate character months "Jan" into numeric "1"

d.GN.month= left_join(d.GN.month, look.up, by = "month")
d.GN.month$day=1

#joins the numeric month values to the dataframe by match month name to number value
#add arbitray day to date to make plotting easier

x=paste(d.GN.month$day, d.GN.month$month.num, d.GN.month$Year, sep = "-")
#this will become our date  column

d.GN.month$date=as.Date(x, format="%d-%m-%Y" )
#creates column "dates""  as class "Date" - this is just to make plotting easier

```

```{r plot_1}
#A plot of all the species - this is a bit horrible to look at
quartz()
ggplot(data=d.GN.month, aes(x= date, y=log(catch), col=as.factor(Species)))+
  geom_line()
```


```{r plot_2}
#plot of only Primera Grande 
#dashed line is the mean

PG=ggplot(subset(d.GN.month, d.GN.month$Species=="PRIMERA GDE."), aes(x= date, y=catch))+
  geom_line()+
  geom_hline(data=subset(d.GN.month, d.GN.month$Species=="PRIMERA GDE."), yintercept = mean(d.GN.month$catch), lty=2)+
  theme_minimal()

PG+geom_line(data=subset(d.GN.month, d.GN.month$Species=="PRIMERA PEQ."), aes(x= date, y=catch), col="red")
  
```

```{r}


```


