---
title: "FF catch curve"
author: "Alex Smith"
date: "October 24, 2016"
output: html_document
---
##Setup

```{r setup, message=FALSE, warning=FALSE}
rm(list=ls())

library(dplyr)
library(tidyr)
library(reshape)
library(ggplot2)
library(lubridate)
library(plotly)

sapply(list.files(pattern="[.]R$", path="./Functions", full.names=TRUE), source)

``` 


```{r length_dist_2012}

corvina.all.2012.short<- read.csv('./data/RAW/Length_2012/corvina_length_monthly_2012.csv') 
corvina.all.2012.short$date = as.Date(corvina.all.2012.short$date, "%m/%d/%y")

corvina.all.2012 <- untable(corvina.all.2012.short[ , c(1,4)], num=corvina.all.2012.short[ ,5]) %>%
  mutate(label = month.abb[month(date)])

```

```{r LH}

LH <- as.data.frame(matrix(data = NA, nrow = 1, ncol = 3))
  colnames(LH) = c("Linf", "to", "K")

LH$Linf <- 122.1

LH$to <- 0.919

LH$K <- 0.172

```

```{r}

ggplot(corvina.all.2012, aes(x=length_class)) +
  geom_histogram(binwidth = 1, colour = "darkgreen", fill = "darkgreen") +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank() ,axis.line = element_line(colour = "black")) +
  theme(axis.text.x = element_text(size=17),
        axis.text.y = element_text(size=17),
        axis.title.x = element_text(size=18),
        axis.title.y = element_text(size=18)) +
labs(x = "Length (cm)")

```

```{r}

corvina.all.2012$age_class <- to - (1/K) * log(1- corvina.all.2012$length_class /Linf) 

ggplot(corvina.all.2012, aes(x=age_class)) +
  geom_histogram(binwidth = 1, colour = "darkblue", fill = "darkblue") +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank() ,axis.line = element_line(colour = "black")) +
  theme(axis.text.x = element_text(size=17),
        axis.text.y = element_text(size=17),
        axis.title.x = element_text(size=18),
        axis.title.y = element_text(size=18)) +
labs(x = "Age (years)")
```

```{r}

CatchCurve(corvina.all.2012$length_class, LH)


M <- 0.3

F <- Z-M 


FFmsy <- F/M

p1

```

