---
title: "Data Managment (spring)"
author: "Alex Smith"
date: "April 19, 2016"
output: ioslides_presentation
incremental: yes
font-family: Helvetica
strip.white: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

##Slack

[Group Slack](https://nicoyafisheries.slack.com/messages/data-analysis/team/alex/)

- Send out invitations (should be same email you use for LAFF)
  
We'll come back to Slack later

## Literature
**Zotero**

[Our Group Library](https://www.zotero.org/groups/509456)

   
  
**Sync Up**

- Create Username (record in google sheet)
- Login to Desktop Zotero
    - Example: add pdf & retrieve metadata
- Join Group library
- Add Chrome plugin

## Github

[NICOYAfisheries](https://github.com/nicoyafisheries)

- Join Group
- Load Repository into your local machines
- Check with push & pull
  
Do we want to pay to make this private?


## More Github 

- Importance of commit message
- Please never put any spaces in file names
- data_scripts folder 
    - Example: catch data
- Using [issues](https://github.com/nicoyafisheries/nicoyafisheries.github.io/issues)
- Links to html outputs 

  Feedback?

## Google Calendars

[Calendars in all their glory](https://calendar.google.com/calendar/render?tab=mc&pli=1#main_7)

Share your calendar with 

  - aedwards.smith@gmail.com
  - diana.f3010@gmail.com
  - mgrivera@uc.cl
  - wagner@biocenosismarina.org
  
  

Check out the GP deadlines calendar  
  
We all have access to edit this  
A notifcation will be sent to slack for every change on this calendar (general channel)  


##Google Drive

- Check-in with Wagner: local folders updating?
- Agree on strorage
  -Do we need additional/fewer folders?
- Discuss Markdown vs Google Docs

Fun fact: this folder is linked with our Slack

## Okay back to [Slack](https://nicoyafisheries.slack.com/messages/data-analysis/team/alex/)

- Review Github integreation
- Review Calendar integration
- Review quick poll
- Agree on channels
- Agree when to use slack for communication

On your own: Check out the desktop App

## Feedback?
