---
author: "Alex Smith"
date: "2/5/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

load('BurnIn.RData')
```


```{r} 

# 2012 plot

comp2012 = BurnIn[c(1,3),] %>%
  gather(Age, Count,3:20) 
comp2012$Count <- round(comp2012$Count)
comp2012$Age <- c(rep(1:18, each=2))

ggplot(comp2012,aes(x=Age,y=Count,fill=Type)) + 
        geom_bar(stat="identity",position = "identity", alpha=.3)+
  ggtitle("2012")
  
# 2012 Chi sq

Model_2012<- t(round(BurnIn[1, 3:20]))
Actual_2012<- t(BurnIn[3, 3:20])

contingency_2012 <- cbind(Model_2012, Actual_2012)
colnames(contingency_2012) <- c("Model", "Actual")
rownames(contingency_2012) <- c(seq(1:18))

contingency_2012NZ <- contingency_2012[1:11,] 
chisq.test(contingency_2012NZ)


```
```{r}

# 2014 plot

comp2014 = BurnIn[c(2,4),] %>%
  gather(Age, Count,3:20) 
comp2014$Count <- round(comp2014$Count)
comp2014$Age <- c(rep(1:18, each=2))

ggplot(comp2014,aes(x=Age,y=Count,fill=Type)) + 
        geom_bar(stat="identity",position = "identity", alpha=.3)+
  ggtitle("2014")
  
# 2014 Chi sq

Model_2014<- t(round(BurnIn[2, 3:20]))
Actual_2014<- t(BurnIn[4, 3:20])

contingency_2014 <- cbind(Model_2014, Actual_2014)
colnames(contingency_2014) <- c("Model", "Actual")
rownames(contingency_2014) <- c(seq(1:18))

chisq.test(contingency_2014)

```

